#!/usr/bin/env bash
set -euo pipefail

# CheetCode v2 — Local Development Setup
# Generates secrets, writes .env.local, and configures Convex.

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env.local"

echo ""
echo "  CheetCode v2 — Local Setup"
echo "  ─────────────────────────────"
echo ""

# ── 1. Install dependencies ──────────────────────────────────────────────────

if [ ! -d "$ROOT/node_modules" ]; then
  echo "→ Installing dependencies..."
  npm install --prefix "$ROOT"
  echo ""
fi

# ── 2. Check for Convex deployment ───────────────────────────────────────────

if [ ! -f "$ENV_FILE" ] || ! grep -q "NEXT_PUBLIC_CONVEX_URL" "$ENV_FILE" 2>/dev/null; then
  echo "→ No Convex deployment found."
  echo ""
  echo "  Run this in a separate terminal first:"
  echo ""
  echo "    npx convex dev"
  echo ""
  echo "  It will prompt you to log in and create a project."
  echo "  Once it's running, re-run this script."
  echo ""
  exit 1
fi

echo "→ Convex deployment found in .env.local"

# ── 3. Generate secrets ─────────────────────────────────────────────────────

generate_secret() {
  node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
}

MUTATION_SECRET=""
SERVER_SECRET=""
DEV_USER="${1:-}"

# Check if secrets already exist
if grep -q "CONVEX_MUTATION_SECRET=" "$ENV_FILE" 2>/dev/null && \
   grep -q "SERVER_SECRET=" "$ENV_FILE" 2>/dev/null && \
   grep -q "DEV_USER=" "$ENV_FILE" 2>/dev/null; then
  echo "→ Environment variables already configured."
  echo ""
  echo "  To reconfigure, delete .env.local and start over."
  echo "  To start the app: npm run dev"
  echo ""
  exit 0
fi

# Prompt for DEV_USER if not passed as argument
if [ -z "$DEV_USER" ]; then
  printf "→ Enter a GitHub username for local dev (skips OAuth): "
  read -r DEV_USER
  if [ -z "$DEV_USER" ]; then
    DEV_USER="local-dev"
  fi
fi

MUTATION_SECRET=$(generate_secret)
SERVER_SECRET=$(generate_secret)

echo "→ Generated CONVEX_MUTATION_SECRET"
echo "→ Generated SERVER_SECRET"

# ── 4. Append to .env.local ─────────────────────────────────────────────────

{
  echo ""
  echo "# ── CheetCode secrets (generated by scripts/setup.sh) ──"
  echo "CONVEX_MUTATION_SECRET=$MUTATION_SECRET"
  echo "SERVER_SECRET=$SERVER_SECRET"
  echo "DEV_USER=$DEV_USER"
} >> "$ENV_FILE"

echo "→ Updated .env.local"

# ── 5. Set Convex environment variable ───────────────────────────────────────

echo "→ Setting CONVEX_MUTATION_SECRET on Convex..."
npx convex env set CONVEX_MUTATION_SECRET "$MUTATION_SECRET" 2>/dev/null || {
  echo ""
  echo "  ⚠ Could not set Convex env var automatically."
  echo "  Run manually:"
  echo ""
  echo "    npx convex env set CONVEX_MUTATION_SECRET $MUTATION_SECRET"
  echo ""
}

# ── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo "  ✓ Setup complete!"
echo ""
echo "  Start developing:"
echo ""
echo "    Terminal 1:  npx convex dev"
echo "    Terminal 2:  npm run dev"
echo ""
echo "  Then open http://localhost:3000"
echo ""
